name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Display the current dir
      run: echo $PWD
      shell: bash
    - name: create configure script
      run: echo > configure
      shell: bash
    - name: list stuff in the dir
      run: ls -la
      shell: bash
    - name: setPermissionToMaximum
      run: |
        chmod a+x configure
      shell: bash {0}
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
